---
name: GitHub Release

on:
  push:
    tags: ["v*"]

permissions: {}

jobs:
  create_release:
    name: Create GitHub release
    runs-on: ubuntu-24.04
    permissions:
      contents: write  # Create the draft release.
    steps:
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"
        shell: bash
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Python 3.13
        uses: actions/setup-python@v7
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install commitizen czespressif
      - name: Generate changelog
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          cz changelog "$VERSION" --file-name changelog_body.md
          cat changelog_body.md
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65  # v2.6.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: changelog_body.md
          name: Version ${{ steps.get_version.outputs.VERSION }}
          draft: true
          prerelease: false
